apiVersion: apps/v1
kind: Deployment
metadata:
  name: pedidos-app
  labels:
    app: pedidos-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pedidos-app
  template:
    metadata:
      labels:
        app: pedidos-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: node-app
        image: devatron/tc-2023-repo:latest        
        envFrom:
          - configMapRef:
              name: app-cm      
        ports:
        - name: http
          containerPort: 80
        imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux