apiVersion: apps/v1
kind: Deployment
metadata:
  name: pedidos-app
  labels:
    app: pedidos-app
spec:
  selector:
    matchLabels:
      app: pedidos-app
  template:
    metadata:
      labels:
        app: pedidos-app
    spec:
      containers:
      - name: node-app
        image: devatron/tc-2023-repo:latest
        # ... other container configuration
        env:
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: dbport
              key: port
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: dbusername
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: dbpassword
              key: password
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: dbname
              key: database
        # [START cloud_sql_proxy_secret_host]
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: postgres-private-ip
              key: db_host
        # [END cloud_sql_proxy_secret_host]